### PR TITLE
Binary wkb

### LINKED ISSUE #1: support the actual binary representation of wkb
Thank you for this useful library.

Currently, in order to get the actual wkb representation of an object, one has to do:

```py
bytes.fromhex(geo.wkb)
```

It would be both more efficient and more intuitive if `geo.wkb` contained directly the Well-Known **Binary** representation of the geometry. The string representation of the wkb could still be obtained with : 

```py
geo.wkb.hex()
```

What do you think about this change ? Would you be opened to a pull request ?

### PR DESCRIPTION
**Pull request by lovasoa**
Fixes #1

### CODE REVIEW

**Comment by lovasoa** [comment]
@bosth : This is ready for review. To make sure I did not break anything, I also improved the tests, and added them to a github action so that they are run automatically.

**Comment by bosth** [comment]
Skimmed it and looks good but I'll do a closer review later. Thanks for the contributions.

**Comment by lovasoa** [comment]
Thank you for merging this ! 
Could you please release it to pypi ?

https://pypi.org/project/plpygis/ still indicates the old version.

**Comment by bosth** [comment]
Yup, I just want to clean up setup.py and a couple of other small things around testing, and then I'll release a new version.

**Comment by bosth** [comment]
Released.

**Pull request merged**
